import {groupEntries, sampleCase, validROI, estimateROI, LEVELS} from './data.js';
const $ = id => document.getElementById(id);
const viewIds=['ap','lateral','apPatch','lateralPatch'];
const viewNames={ap:'AP',lateral:'LAT',apPatch:'AP PATCH',lateralPatch:'LAT PATCH'};
const defaults=()=>({zoom:1,panX:0,panY:0,rotation:0,flip:false,invert:false,brightness:100,contrast:100});
const state={cases:[],current:null,active:'ap',tool:'pan',generation:0,analysis:0,analyzed:false,ready:false,busy:false,focused:null,urls:[],draft:null};
const views=Object.fromEntries(viewIds.map(id=>[id,{id,canvas:$('canvas-'+id),img:null,...defaults()}]));
let toastTimer,framePending=false;
function notify(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4200);}
function status(message){$('status-message').textContent=message;}
function scheduleDraw(){if(framePending)return;framePending=true;requestAnimationFrame(()=>{framePending=false;viewIds.forEach(drawView);});}
function geometry(v){const area=v.canvas.parentElement,w=area.clientWidth,h=area.clientHeight;const fit=v.img?Math.min((w-24)/v.img.naturalWidth,(h-24)/v.img.naturalHeight):1;return {w,h,scale:Math.max(.0001,fit)*v.zoom,cx:w/2+v.panX,cy:h/2+v.panY,rad:v.rotation*Math.PI/180};}
function screenPoint(v,x,y){const g=geometry(v);const dx=(x-v.img.naturalWidth/2)*(v.flip?-1:1),dy=y-v.img.naturalHeight/2;return {x:g.cx+g.scale*(dx*Math.cos(g.rad)-dy*Math.sin(g.rad)),y:g.cy+g.scale*(dx*Math.sin(g.rad)+dy*Math.cos(g.rad))};}
function imagePoint(v,x,y){const g=geometry(v),dx=(x-g.cx)/g.scale,dy=(y-g.cy)/g.scale;return {x:(dx*Math.cos(g.rad)+dy*Math.sin(g.rad))*(v.flip?-1:1)+v.img.naturalWidth/2,y:-dx*Math.sin(g.rad)+dy*Math.cos(g.rad)+v.img.naturalHeight/2};}
function roiFor(id){return state.current?.views[id]?.roi;}
function drawROI(v,roi,draft=false){if(!validROI(roi))return;const W=v.img.naturalWidth,H=v.img.naturalHeight;const [x,y,w,h]=roi;const points=[[x*W,y*H],[(x+w)*W,y*H],[(x+w)*W,(y+h)*H],[x*W,(y+h)*H]].map(p=>screenPoint(v,...p));const ctx=v.canvas.getContext('2d');ctx.strokeStyle=draft?'#51c8ff':'#50f7a2';ctx.lineWidth=1.4;ctx.setLineDash(draft?[4,3]:[]);ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();ctx.setLineDash([]);const p=points.reduce((a,b)=>a.y<b.y?a:b);ctx.font='10px Arial';const label=draft?'ROI':'SHUNT VALVE';const tw=ctx.measureText(label).width+10,tx=Math.min(Math.max(2,p.x),geometry(v).w-tw-2),ty=Math.max(15,p.y-4);ctx.fillStyle=draft?'#193d53':'#153d2c';ctx.fillRect(tx,ty-13,tw,15);ctx.fillStyle=draft?'#85d7ff':'#6ffbb3';ctx.fillText(label,tx+5,ty-2);}
function drawView(id){const v=views[id],g=geometry(v);if(g.w<1||g.h<1)return;const dpr=Math.min(devicePixelRatio||1,2);const width=Math.round(g.w*dpr),height=Math.round(g.h*dpr);if(v.canvas.width!==width||v.canvas.height!==height){v.canvas.width=width;v.canvas.height=height;}const ctx=v.canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#010405';ctx.fillRect(0,0,g.w,g.h);if(v.img){ctx.save();ctx.translate(g.cx,g.cy);ctx.rotate(g.rad);ctx.scale(g.scale*(v.flip?-1:1),g.scale);ctx.filter=`brightness(${v.brightness}%) contrast(${v.contrast}%)${v.invert?' invert(1)':''}`;ctx.drawImage(v.img,-v.img.naturalWidth/2,-v.img.naturalHeight/2);ctx.restore();if(state.analyzed&&$('show-roi').checked&&['ap','lateral'].includes(id))drawROI(v,roiFor(id));if(state.draft?.id===id)drawROI(v,state.draft.roi,true);} $('info-'+id).textContent=Math.round(v.zoom*100)+'% · '+v.rotation+'°'+(v.flip?' · FLIP':'');}
function syncControls(){const v=views[state.active];$('rotation').value=v.rotation;$('rotation-value').textContent=v.rotation+'°';$('brightness').value=v.brightness;$('brightness-value').textContent=v.brightness+'%';$('contrast').value=v.contrast;$('contrast-value').textContent=v.contrast+'%';$('zoom-value').textContent=Math.round(v.zoom*100)+'%';$('control-target').textContent=viewNames[state.active];$('active-view').textContent=viewNames[state.active]+' 선택됨';$('flip-x').classList.toggle('active',v.flip);$('invert').classList.toggle('active',v.invert);}
function activate(id){state.active=id;viewIds.forEach(v=>$('view-'+v).classList.toggle('selected',v===id));syncControls();}
function rotate(delta){const v=views[state.active];v.rotation=((v.rotation+delta+540)%360)-180;syncControls();scheduleDraw();}
function zoomAt(id,factor,x,y){const v=views[id];if(!v.img)return;const g=geometry(v);x??=g.w/2;y??=g.h/2;const anchor=imagePoint(v,x,y);v.zoom=Math.min(24,Math.max(.15,v.zoom*factor));const after=screenPoint(v,anchor.x,anchor.y);v.panX+=x-after.x;v.panY+=y-after.y;syncControls();scheduleDraw();}
function fit(id,all=false){Object.assign(views[id],all?defaults():{zoom:1,panX:0,panY:0});syncControls();scheduleDraw();}
function focusView(id){state.focused=state.focused===id?null:id;document.querySelector('.image-grid').classList.toggle('focused',!!state.focused);viewIds.forEach(v=>$('view-'+v).classList.toggle('focused',state.focused===v));activate(id);scheduleDraw();}
function setTool(tool){state.tool=tool;document.body.dataset.tool=tool;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('interaction-hint').textContent={pan:'휠: 확대/축소 · 드래그: 이동 · 더블클릭: 화면 맞춤',zoom:'상하 드래그 또는 마우스 휠로 확대/축소',window:'좌우 드래그: 대비 · 상하 드래그: 밝기',roi:'AP 또는 LAT 원본에서 밸브를 둘러싸도록 드래그'}[tool];}
function cancelAnalysis(){state.analysis++;state.busy=false;document.querySelectorAll('.viewport').forEach(v=>v.classList.remove('analyzing'));$('progress-fill').style.transition='none';$('progress-fill').style.width='0';}
function clearResult(){state.analyzed=false;$('result-level').textContent='—';document.querySelector('.result-number').classList.remove('complete');$('result-state').textContent='분석 대기';$('processing-time').textContent='—';$('analysis-state').textContent='READY';$('analyze-label').textContent='AI 분석 실행';document.querySelectorAll('[data-level]').forEach(el=>el.classList.remove('selected'));['ap','lateral'].forEach(id=>{$('roi-state-'+id).textContent='대기';document.querySelector('[data-zoom-roi="'+id+'"]').disabled=true;});$('roi-message').textContent='분석 후 원본 영상에 밸브 영역 표시';}
function loadImage(url){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('이미지 읽기 실패'));image.src=url;});}
function renderCases(){const query=$('case-search').value.trim().toLowerCase();$('case-list').replaceChildren();const matches=state.cases.filter(c=>(c.id+' '+c.key).toLowerCase().includes(query));for(const c of matches){const button=document.createElement('button');button.className='case-item'+(state.current?.key===c.key?' selected':'');button.setAttribute('aria-label',c.id+' 사례 열기');const row=document.createElement('div');row.className='case-title-row';const title=document.createElement('span');title.textContent=c.id;const badge=document.createElement('span');badge.className='case-status';badge.textContent=c.complete?'AP / LAT':'미완성';row.append(title,badge);const images=document.createElement('div');images.className='case-images';for(const id of ['ap','lateral']){if(!c.views[id]?.image)continue;const im=document.createElement('img');im.src=c.views[id].image;im.alt=id==='ap'?'정면 썸네일':'측면 썸네일';im.loading='lazy';images.append(im);}const description=document.createElement('small');description.textContent=c.source==='sample'?'VIRTUAL SAMPLE · 예시':'PAIRED SKULL RADIOGRAPHS';button.append(row,images,description);button.addEventListener('click',()=>selectCase(c));$('case-list').append(button);}if(!matches.length){const p=document.createElement('div');p.className='no-cases';p.textContent='검색 결과가 없습니다.';$('case-list').append(p);} $('case-count').textContent=state.cases.length;}
async function selectCase(c){cancelAnalysis();clearResult();state.current=c;state.ready=false;const generation=++state.generation;state.draft=null;$('analyze').disabled=true;$('study-title').textContent=c.id;$('study-tag').textContent=c.source==='sample'?'VIRTUAL SAMPLE':'2 VIEWS';$('meta-ap').textContent=c.id;$('meta-lateral').textContent=c.id;renderCases();for(const id of viewIds){Object.assign(views[id],defaults(),{img:null});$('empty-'+id).hidden=false;$('empty-'+id).textContent='영상 불러오는 중';}status('Loading images…');scheduleDraw();
  const mappings={ap:c.views.ap?.image,lateral:c.views.lateral?.image,apPatch:c.views.ap?.patch,lateralPatch:c.views.lateral?.patch};
  const settled=await Promise.all(viewIds.map(async id=>{try{return {id,image:mappings[id]?await loadImage(mappings[id]):null};}catch{return {id,image:null};}}));if(generation!==state.generation)return;
  for(const {id,image} of settled){views[id].img=image;views[id].zoom=id.endsWith('Patch')?1.8:1;$('empty-'+id).hidden=!!image;$('empty-'+id).textContent=id.endsWith('Patch')?'패치 없음':'원본 영상 없음';if(['ap','lateral'].includes(id))$('dims-'+id).textContent=image?image.naturalWidth+' × '+image.naturalHeight:'';}
  activate('ap');scheduleDraw();status('Preparing valve locations…');
  for(const id of ['ap','lateral']){const entry=c.views[id];if(!entry)continue;if(!validROI(entry.roi)&&views[id].img&&views[id+'Patch'].img){try{const match=await estimateROI(views[id].img,views[id+'Patch'].img);if(generation!==state.generation)return;if(match){entry.roi=match.roi;entry.roiSource=match.source;}}catch{/* Manual ROI remains available. */}}}
  if(generation!==state.generation)return;state.ready=!!views.ap.img&&!!views.lateral.img;const hasErrors=c.errors?.some(e=>!e.includes('원본 누락'));$('analyze').disabled=!state.ready||!!hasErrors;$('analysis-state').textContent=state.ready?'READY':'INCOMPLETE';status(hasErrors?'데이터 확인 필요 · '+c.errors.join(' / '):state.ready?'Viewer ready · '+c.id:'정면·측면 원본이 모두 필요합니다.');scheduleDraw();
}
function installDataset(cases,name,source){cancelAnalysis();++state.generation;state.cases=cases;state.current=null;$('case-search').value='';$('dataset-name').textContent=name;$('source-summary').textContent=source;$('dataset-count').textContent=cases.length+' studies · paired views';if(cases.length)selectCase(cases[0]);else renderCases();}
function releaseURLs(){state.urls.forEach(URL.revokeObjectURL);state.urls=[];}
function sample(){releaseURLs();installDataset([structuredClone(sampleCase)],'가상 예시 데이터','가상 도식 · 단계 1.0');}
async function repositoryData(showMessage=false){status('Loading repository data…');try{const response=await fetch('./data/manifest.json',{cache:'no-store'});if(!response.ok)throw new Error('no-manifest');const manifest=await response.json();if(!Array.isArray(manifest.cases)||!manifest.cases.length)throw new Error('empty');const cases=manifest.cases.map((c,i)=>({...c,id:'CASE '+String(i+1).padStart(3,'0'),source:'repository',complete:!!c.views?.ap?.image&&!!c.views?.lateral?.image,level:LEVELS.includes(Number(c.level))&&c.level!==null?Number(c.level):null,errors:c.errors||[]}));releaseURLs();installDataset(cases,'shunt_data',cases.length+'개 사례 · 저장소 데이터');if(showMessage)notify(cases.length+'개 사례를 불러왔습니다.');if(manifest.warnings?.length)notify('일부 파일 확인 필요: '+manifest.warnings.length+'건 · README 및 manifest 참조');}catch{if(!state.cases.length)sample();else status('Viewer ready');if(showMessage)notify('저장소 데이터가 아직 없습니다. 폴더 열기로 shunt_data를 선택할 수 있습니다.');}}
function finishLocalization(){let found=0;for(const id of ['ap','lateral']){const exists=validROI(roiFor(id));if(exists)found++;$('roi-state-'+id).textContent=exists?'위치 표시':'영역 미지정';document.querySelector('[data-zoom-roi="'+id+'"]').disabled=!exists;} $('roi-message').textContent=found===2?'패치 기반 위치 · 필요 시 영역 지정으로 보정':'위치를 지정하려면 원본 영상에서 영역 지정 도구 사용';if(state.current.source==='sample')$('roi-message').textContent='가상 도식에 준비된 밸브 위치';}
async function analyze(){if(!state.ready||state.busy||$('analyze').disabled)return;cancelAnalysis();const token=state.analysis;state.busy=true;clearResult();$('analyze').disabled=true;$('analyze-label').textContent='분석 중…';$('analysis-state').textContent='PROCESSING';document.querySelectorAll('#view-ap,#view-lateral').forEach(v=>v.classList.add('analyzing'));$('progress-fill').style.transition='width 220ms linear';$('progress-fill').style.width='100%';status('Analyzing…');await new Promise(resolve=>setTimeout(resolve,220));if(token!==state.analysis)return;state.busy=false;state.analyzed=true;document.querySelectorAll('.viewport').forEach(v=>v.classList.remove('analyzing'));$('analyze').disabled=false;$('analyze-label').textContent='다시 분석';$('analysis-state').textContent='COMPLETE';const level=state.current.level;$('result-level').textContent=level===null?'—':Number(level).toFixed(1);document.querySelector('.result-number').classList.toggle('complete',level!==null);$('result-state').textContent=level===null?'단계 정보 없음':'분석 완료';$('processing-time').textContent='0.22 s';document.querySelectorAll('[data-level]').forEach(el=>el.classList.toggle('selected',level!==null&&Number(el.dataset.level)===Number(level)));finishLocalization();status('Demo analysis complete · 220 ms');scheduleDraw();}
function zoomROI(id){const v=views[id],roi=roiFor(id);if(!v.img||!validROI(roi))return;activate(id);const [x,y,w,h]=roi;const g=geometry(v),base=g.scale/v.zoom;v.zoom=Math.min(24,Math.max(1,Math.min(g.w*.55/(w*v.img.naturalWidth),g.h*.55/(h*v.img.naturalHeight))/base));v.panX=0;v.panY=0;const p=screenPoint(v,(x+w/2)*v.img.naturalWidth,(y+h/2)*v.img.naturalHeight);v.panX=g.w/2-p.x;v.panY=g.h/2-p.y;syncControls();scheduleDraw();}
function setManualROI(id,roi){if(!validROI(roi)||roi[2]<.005||roi[3]<.005)return;state.current.views[id].roi=roi;state.current.views[id].roiSource='manual';if(state.analyzed)finishLocalization();notify(viewNames[id]+' 밸브 영역을 지정했습니다.');scheduleDraw();}
function exportResult(){const canvas=document.createElement('canvas');canvas.width=1500;canvas.height=930;const ctx=canvas.getContext('2d');ctx.fillStyle='#111820';ctx.fillRect(0,0,1500,930);ctx.fillStyle='#c9e6f2';ctx.font='bold 27px Arial';ctx.fillText('ShuntView | '+(state.current?.id||'DEMO'),30,45);ctx.font='16px Arial';ctx.fillStyle='#e0b16c';ctx.fillText('DEMO — prepared results, no model inference',30,76);const positions=[[20,100,720,485],[760,100,720,485],[20,605,720,235],[760,605,720,235]];viewIds.forEach((id,i)=>{const [x,y,w,h]=positions[i];ctx.fillStyle='#9dc6d8';ctx.font='13px Arial';ctx.fillText(viewNames[id],x+10,y+15);const c=views[id].canvas,scale=Math.min(w/c.width,(h-25)/c.height);ctx.drawImage(c,x+(w-c.width*scale)/2,y+25,c.width*scale,c.height*scale);});ctx.fillStyle='#5bffac';ctx.font='bold 25px Arial';ctx.fillText('Performance Level: '+(state.analyzed&&state.current.level!==null?Number(state.current.level).toFixed(1):'—'),30,891);ctx.font='13px Arial';ctx.fillStyle='#8baab9';ctx.fillText('Demonstration only · not for clinical decisions',1020,893);canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='shuntview_'+(state.current?.id||'demo').replaceAll(' ','_')+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}

// Mouse/touch interaction is applied only to the selected image viewport.
for(const id of viewIds){const v=views[id];let drag=null;v.canvas.addEventListener('pointerdown',event=>{if(!v.img||event.button!==0)return;activate(id);const rect=v.canvas.getBoundingClientRect(),p={x:event.clientX-rect.left,y:event.clientY-rect.top};if(state.tool==='roi'&&id.endsWith('Patch')){notify('밸브 영역은 AP 또는 LAT 원본에서 지정해 주세요.');return;}v.canvas.setPointerCapture(event.pointerId);v.canvas.classList.add('dragging');drag={pointer:event.pointerId,start:p,last:p,panX:v.panX,panY:v.panY,brightness:v.brightness,contrast:v.contrast,startImage:imagePoint(v,p.x,p.y)};});
v.canvas.addEventListener('pointermove',event=>{if(!drag||drag.pointer!==event.pointerId)return;const rect=v.canvas.getBoundingClientRect(),p={x:event.clientX-rect.left,y:event.clientY-rect.top};if(state.tool==='pan'){v.panX=drag.panX+p.x-drag.start.x;v.panY=drag.panY+p.y-drag.start.y;}else if(state.tool==='zoom')zoomAt(id,Math.exp((drag.last.y-p.y)*.012),drag.start.x,drag.start.y);else if(state.tool==='window'){v.brightness=Math.min(250,Math.max(25,Math.round(drag.brightness+(drag.start.y-p.y)*.7)));v.contrast=Math.min(300,Math.max(25,Math.round(drag.contrast+(p.x-drag.start.x)*.7)));}else{const end=imagePoint(v,p.x,p.y),W=v.img.naturalWidth,H=v.img.naturalHeight;const x1=Math.max(0,Math.min(W,drag.startImage.x)),y1=Math.max(0,Math.min(H,drag.startImage.y)),x2=Math.max(0,Math.min(W,end.x)),y2=Math.max(0,Math.min(H,end.y));state.draft={id,roi:[Math.min(x1,x2)/W,Math.min(y1,y2)/H,Math.abs(x2-x1)/W,Math.abs(y2-y1)/H]};}drag.last=p;syncControls();scheduleDraw();});
const endDrag=event=>{if(!drag||drag.pointer!==event.pointerId)return;if(state.draft?.id===id&&event.type!=='pointercancel')setManualROI(id,state.draft.roi);state.draft=null;drag=null;v.canvas.classList.remove('dragging');if(v.canvas.hasPointerCapture(event.pointerId))v.canvas.releasePointerCapture(event.pointerId);scheduleDraw();};v.canvas.addEventListener('pointerup',endDrag);v.canvas.addEventListener('pointercancel',endDrag);v.canvas.addEventListener('wheel',event=>{event.preventDefault();activate(id);const rect=v.canvas.getBoundingClientRect();zoomAt(id,Math.exp(-event.deltaY*.0015),event.clientX-rect.left,event.clientY-rect.top);},{passive:false});v.canvas.addEventListener('dblclick',()=>fit(id));$('view-'+id).addEventListener('focus',()=>activate(id));}
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));
$('rotate-left').addEventListener('click',()=>rotate(-90));$('rotate-right').addEventListener('click',()=>rotate(90));$('fine-left').addEventListener('click',()=>rotate(-1));$('fine-right').addEventListener('click',()=>rotate(1));
$('flip-x').addEventListener('click',()=>{views[state.active].flip=!views[state.active].flip;syncControls();scheduleDraw();});$('invert').addEventListener('click',()=>{views[state.active].invert=!views[state.active].invert;syncControls();scheduleDraw();});$('fit').addEventListener('click',()=>fit(state.active));$('reset').addEventListener('click',()=>fit(state.active,true));$('zoom-in').addEventListener('click',()=>zoomAt(state.active,1.25));$('zoom-out').addEventListener('click',()=>zoomAt(state.active,.8));
for(const key of ['rotation','brightness','contrast'])$(key).addEventListener('input',()=>{views[state.active][key]=Number($(key).value);syncControls();scheduleDraw();});
document.querySelectorAll('[data-focus]').forEach(b=>b.addEventListener('click',()=>focusView(b.dataset.focus)));document.querySelectorAll('[data-zoom-roi]').forEach(b=>b.addEventListener('click',()=>zoomROI(b.dataset.zoomRoi)));$('show-roi').addEventListener('change',scheduleDraw);$('analyze').addEventListener('click',analyze);$('case-search').addEventListener('input',renderCases);$('sample-btn').addEventListener('click',sample);$('reload-data').addEventListener('click',()=>repositoryData(true));$('folder-btn').addEventListener('click',()=>$('folder-input').click());
$('folder-input').addEventListener('change',event=>{const files=[...event.target.files];if(!files.length)return;const newURLs=[];const entries=files.map(file=>{const url=URL.createObjectURL(file);newURLs.push(url);return {path:file.webkitRelativePath||file.name,url};});const {cases,warnings}=groupEntries(entries);if(!cases.length){newURLs.forEach(URL.revokeObjectURL);notify('anterior/images, lateral/images 구조의 shunt_data 폴더를 선택해 주세요.');event.target.value='';return;}releaseURLs();state.urls=newURLs;installDataset(cases,'shunt_data · LOCAL',cases.length+'개 사례 · PC 폴더');if(warnings.length)notify('일부 파일을 확인해 주세요. '+warnings.length+'개 사례에 누락 또는 중복이 있습니다.');event.target.value='';});
$('export').addEventListener('click',exportResult);$('help-btn').addEventListener('click',()=>$('help-dialog').showModal());$('help-close').addEventListener('click',()=>$('help-dialog').close());$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('브라우저 전체 화면(F11)을 사용해 주세요.');}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&state.focused){const id=state.focused;focusView(id);}});new ResizeObserver(scheduleDraw).observe(document.querySelector('.image-grid'));window.addEventListener('resize',scheduleDraw);document.addEventListener('fullscreenchange',scheduleDraw);setTool('pan');repositoryData();
